go update

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,12 +15,46 @@ runs:
       with:
         ref: "main"
 
-    - name: git
+    - name: check rc and merge
       run: |
-        git checkout -b "rc/${{ inputs.tag }}"
-        git push --set-upstream origin "rc/${{ inputs.tag }}"
+        #!/usr/bin/env bash
+
+        git config user.name "GitHub Actions Bot"
+        git config user.email "devops@atarb2b.com"
+        git fetch --all
+
+        fc_branch=$(git symbolic-ref --short HEAD)
+
+        get_hash() {
+          git rev-parse --short "$1" || true
+        }
+
+        fc_branch_hash=$(get_hash "$fc_branch")
+        rc_branch_hash=$(get_hash "rc/${{ inputs.tag }}")
+
+        if [ "$fc_branch_hash" = "$rc_branch_hash" ]; then
+          echo "Can't merge. fc branch is equal to the rc branch."
+          exit 1
+        fi
+
+        if [ -z "$rc_branch_hash" ]; then
+        
+          echo "rc branch not found."
+          
+          git checkout -b "rc/${{ inputs.tag }}"
+          git push --set-upstream origin "rc/${{ inputs.tag }}"
+        
+        else
+          
+          echo "rc/${{ inputs.tag }} alredy exists, go to merge."
+          
+          git checkout --quiet "$fc_branch_hash"
+          git merge "rc/${{ inputs.tag }}" -m "Merge Commit Auto." || true
+          git push --set-upstream origin "rc/${{ inputs.tag }}"
+        
+        fi
       shell: bash
-    
+
     - name: Send Message to Slack
       uses: 8398a7/action-slack@v3
       with:
